# Setup
title: Anupam Upadhyay
tagline: "I know nothing!"
description: "Anupam's personal website."
url: http://anupam128.com
baseurl: ""
paginate: 5
permalink: pretty
# pagination:
#   enabled: true
#   per_page: 5
#   collection: "posts"

# About/contact
author:
  name: Anupam Upadhyay
  email: anupam128@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 0.0.1
google_analytics_id: UA-163710833-1
