# Setup
title: Anupam Upadhyay
tagline: "Stories, essays, and ideas"
description: "Speculative fiction, essays, and curious detours by Anupam Upadhyay."
url: https://anupam128.com
baseurl: ""
permalink: pretty
# pagination:
#   enabled: true
#   per_page: 5
#   collection: "posts"

# About/contact
author:
  name: Anupam Upadhyay
  email: anupam128@gmail.com

# Gems
plugins: []

# Custom vars
version: 0.0.1
google_analytics_id: UA-163710833-1
